# Generated by Django 5.2.6 on 2025-12-15 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('animeId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Título')),
                ('generos', models.TextField(verbose_name='Géneros')),
                ('formatoEmision', models.TextField(help_text='Ejemplo: TV, Movie, OVA, etc.', verbose_name='Formato de emisión')),
                ('numeroEpisodios', models.IntegerField(help_text='Debe introducir un número entero', verbose_name='Número de episodios')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioId', models.IntegerField(verbose_name='ID Usuario')),
                ('puntuacion', models.IntegerField(help_text='Debe introducir un número entre 1 y 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación')),
                ('animeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
            options={
                'ordering': ('-puntuacion',),
                'unique_together': {('usuarioId', 'animeId')},
            },
        ),
    ]
